### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by jgtoriginal** [RX7RUSS/advanced-final-gps#1]
### Steps to reproduce

```
git clone git@github.com:RX7RUSS/advanced-final-gps.git
cd advanced-final-gps
npm i
expo start
```

I also tried updating all packages by running
```
npm i -g npm-check-updates
ncu -u
```

### Expected behavior
See it running

### Actual behavior

![Simulator Screen Shot - iPhone Xʀ - 2019-04-17 at 20 40 30](https://user-images.githubusercontent.com/1785392/56327568-420e7600-6151-11e9-8c7d-ddf118319431.png)

**Comment by RX7RUSS** [comment]
Hey @jgtoriginal this was a final project for my boot camp. I haven't opened this file in a very long time. I know that google has changed their maps api structure and the key in this project would definitely not be valid. As far as all the react-native packages I think the best way to make this work would be to just create a brand new react-native app and copy over the few react/redux folders & files.

**Comment by jgtoriginal** [comment]
oh, good tip. gotcha!
thanks very much for your fast response @RX7RUSS

**Comment by RX7RUSS** [comment]
@jgtoriginal No problem! I apologize for having such an old broken repo up but hopefully, there is something in there for you. I used a firebase database that is still open I believe. If you do get it running the auth is just "Test@test.com" and "password".

Here is a walkthrough video I made back when I built the app:
https://www.youtube.com/watch?v=bKENkfGY5mQ

If you do get some use out of it that's great but since graduating from the boot camp I have been using a lot of Angular and I would highly recommend the Angular Google Maps package if you are trying to do some geolocation work in a web app.
